---

- name: Configure Nginx
  hosts: all
  gather_facts: true
  tasks:
    - name: Copy content
      copy:
        src: index.html
        dest: /usr/share/nginx/html
        owner: root
        group: root
        mode: '0644'
    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: true
